apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubapiapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: githubapiapp
  template:
    metadata:
      labels:
        app: githubapiapp
    spec:
      containers:
        - name: githubapiapp
          image: githubapiapp:latest
          ports:
            - containerPort: 8080